# this is for internal use - do not change it!
# seriously, if you do you can break the plugin
config-version: 1

# set which language file to use. only english is supplied,
# but you can add your own (PRs welcome)
language-file: lang-en.yml

# output extra information to console (can be spammy)
debug-mode: false

# the address your players use for accessing the map
web-address: https://example.com:8080

# settings for the plugin's storage
web-directory:
  # the path where the public web directory is
  # relative paths are from the plugin's directory
  # absolute paths will work here, too
  path: web
  # should the plugin overwrite all the public web files when
  # the plugin starts up set to false if you want to edit the
  # files by hand, but be warned you will have to keep the files
  # updated yourself when internal changes happen
  auto-update: true

# Control the quality of the tile images
image-quality:
  # image format type tiles are stored as
  # currently only PNG is supported
  type: PNG
  # The compression of the tile images
  # (0.0 to favor speed, 1.0 to favor compression)
  # Compression may or may not slow down renders but make
  # smaller file sizes for tiles
  compress-images: 0.0

# the internal web server settings
internal-webserver:
  # set to true to use the plugin's internal web server
  # set to false if you want to run your own external web server
  enabled: true
  # the ip the internal web server will bind to
  # (leave this alone if you don't know what it does)
  bind: 0.0.0.0
  # the port the internal web server will bind to
  port: 8080

# global UI settings
ui:
  # this controls the box showing coordinates on mouse position
  coordinates:
    # show the coordinates box on the map
    enabled: true
  # this is the link box containing a link to the current map view
  link:
    # show the link box on the map
    enabled: true
  # sidebar options
  sidebar:
    # sidebar pin control. possible values are:
    # pinned - default to pulled out and pinned
    # unpinned - default to pushed in and unpinned
    # hide - default to pushed in and hide the pin button
    pinned: pinned
  # player tracker settings
  player-tracker:
    # show players on the map
    enabled: true
    # how often to update the players
    update-interval-seconds: 1
    # show the layer control for player tracker
    show-controls: true
    # hide the layer control (unchecked) by default
    default-hidden: false
    # the priority of the layer control in the control box
    layer-priority: 999
    # the z-index of the player markers on the map
    z-index: 999
    # nameplate settings on player markers
    nameplate:
      # show nameplate on player markers
      enabled: true
      # show player heads in nameplates
      show-head: true
      # The url where player heads are fetched from
      # valid variables are {uuid} and {name}
      heads-url: https://mc-heads.net/avatar/{uuid}/16
      # show player's armor in the nameplate
      show-armor: true
      # show player's health in the nameplate
      show-health: true
    # player hide settings
    hide:
      # hide invisible players (potion)
      invisible: true
      # hide players in spectator gamemode
      spectators: true
