name: "${name}"
main: "${group}.paper.${name}Paper"
description: "${description}"
version: "${version}"
author: "BillyGalbreath"
api-version: "1.17"
website: "https://github.com/pl3xgaming/Pl3xMap/"


permissions:
  pl3xmap.command.map:
    description: Control the Pl3xMap plugin
    default: op

  pl3xmap.command.hide:
    description: Hide yourself from the map
    default: op
    children:
      pl3xmap.command.map: true
  pl3xmap.command.hide.other:
    description: Hide other players from the map
    default: op
    children:
      pl3xmap.command.hide: true

  pl3xmap.command.show:
    description: Show yourself on the map
    default: op
    children:
      pl3xmap.command.map: true
  pl3xmap.command.show.other:
    description: Show other players on the map
    default: op
    children:
      pl3xmap.command.show: true

  pl3xmap.command.reload:
    description: Reload the plugin configs
    default: op
    children:
      pl3xmap.command.map: true
